#!/bin/bash
#source ~/.zshrc
set -e
if [[ $# -ne 1 ]]; then
  echo "usage $0 docx_to_import (run in directory where docx to be unzipped into)"
  exit 1;
fi

docxInPath=$(realpath $1)
docxFn=$(basename $1)
dirName=$(basename $1 .docx)
echo 'docxInPath' $docxInPath 'source file: ' $docxFn ' dest dir ./' $dirName

rm -rf $dirName
echo mkdir "$dirName"
mkdir "$dirName"
cd "$dirName"
cp $docxInPath .
unzip $docxFn
rm $docxFn
find . -type f -name "*.xml" -or -name "*.rels" | while read -r line ; do
    # echo "formatting $line blah!"
    xmllint --format "$line" | sponge "$line"
done
if [ -z "$_sublime_path" ]; then
  _sublime_path="/Applications/Sublime Text.app/Contents/SharedSupport/bin/subl";
  subl () { "$_sublime_path" $*; }
fi
subl word/document.xml
#subl numbering.xml